name: Revert to Build 17
on:
  workflow_dispatch:

jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Revert to commit 2961c84
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git revert --no-commit 2961c84..HEAD
          git commit -m "Revert to Build #17 stable state"
          git push
