name: Print Secrets
on:
  workflow_dispatch:
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Keystore Base64
        run: echo "${{ secrets.KEYSTORE_BASE64 }}"
      
      - name: Print Password and Keys
        run: |
          echo "PASS: ${{ secrets.KEYSTORE_PASSWORD }}"
          echo "ALIAS: ${{ secrets.KEY_ALIAS }}"
          echo "KEYPASS: ${{ secrets.KEY_PASSWORD }}"
